### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by nikolaokonesh** [flippakitten/frap#22]
Work with rails 6 ?

**Comment by flippakitten** [comment]
V1 will work with Rails 6 as the default but you should be able to use it already.

V1 also has much cleaner implementation of the BLoC pattern.

What I'll do for now though is do a minor version bump to upgrade to Rails 6 and Flutter 1.9 although V1 most likely not be backwards compatible, unfortunately.

Future versions will be more compatible and have upgrade paths.

**Comment by flippakitten** [comment]
@nikolaokonesh Just another comment, I see I have already added it to the [Roadmap](https://github.com/flippakitten/frap/projects/2 ). Development came to an abrupt halt as I have been a little busy moving countries.
Will hopefully get cracking again next week, or the week after.

**Comment by flippakitten** [comment]
Closing as Version 0.3.0 uses rails 6.0.1 as the default.
